import type { NextPage } from 'next'
import Head from '../components/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import { useState } from 'react'


const navList = [
  {
    id: '1',
    name: "关注",
    url: '',
  }, {
    id: '2',
    name: '综合',
    url: '',
  }, {
    id: '3',
    name: '后端',
    url: ''
  }, {
    id: '4',
    name: '前端',
    url: ''
  }, {
    id: '5',
    name: 'Android',
    url: ''
  }, {
    id: '6',
    name: 'ios',
    url: ''
  }, {
    id: '7',
    name: '人工智能',
    url: ''
  }, {
    id: '8',
    name: '开发工具',
    url: ''
  }, {
    id: '9',
    name: '代码人生',
    url: ''
  }, {
    id: '10',
    name: '阅读',
    url: ''
  }
]
const Home: NextPage = () => {

  const [nav, setNav] = useState(navList[1]);
  
  
  return (
    <div className={styles.container}>
      {/* 做SSR相关配置 */}
      <Head title='稀土掘金' content="Generated by create next app" iconPath="https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/6c61ae65d1c41ae8221a670fa32d05aa.svg" />
      
      {/* 内容区域 */}
      <main className={styles.main}>
        <Header></Header>

        <div className={styles.content}>
          <div className={styles.navlist}>
            <ul>
              {navList.map(item => {
                return (
                  <li onClick={()=>setNav(item)} className={item.id == nav.id ? styles["navitem-active"] : undefined}  key={item.id}>
                    {item.name}
                  </li>
                )
              })}
            </ul>
          </div>
          <div className={ styles.right_content }>
            <div className={ styles.articlelist }>12</div>
            <div className={ styles.other }>12</div>
          </div>
        </div>
      </main>
      
    </div>
  )
}

export default Home

/* 首页目前不打算做这么多的动能，想法就是简单的做一个左侧导航栏+右侧文章列表，其余部分先占位(方便后期填坑) */
